# Generated by Django 2.2.4 on 2019-08-19 16:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.ImageField(default='', upload_to='post/preview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(upload_to=core.models.folder_avatar),
        ),
    ]
